### PR TITLE
initial attempt at fixing #8

### LINKED ISSUE #8: Component::CurDir missing
I noticed that Component::CurDir is missing, which I was hoping to use as a marker for splitting off a prefix. Having tried Normal(".")... that doesn't ever match, because it looks as though Components::iter(), skips over these via the function scan_separator here:
https://github.com/udoprog/relative-path/blob/master/src/lib.rs#L110-L113

Is this intended to happen before normalize() is called?

### PR DESCRIPTION
**Pull request by ratmice**
Here is (I guess an RFC/initial attempt which likely needs work) to fix #8,
I was fairly surprised that this didn't seem to blow up the testsuite.
and worked with the function below. 

I will try and do another pass at this looking for problems with it.

```rust
fn upto_curdir_rel<P: AsRef<RelativePath>>(foo: P) -> RelativePathBuf {
  let mut leading = RelativePathBuf::new();
  for component in foo.as_ref().components() {
    match component {
        Component::CurDir => break,
        Component::Normal(s) => leading.push(s),
        Component::ParentDir => leading.push(".."),
    }
  }
  leading
}
```

### CODE REVIEW

**Comment by udoprog** [comment]
Hey,

Thanks for the contribution!

So it definitely makes sense to have a `CurDir` component (and eventually a `ParentDir` as well). These are both relatively common constructs for relative paths.

So your change did indeed blow up a couple of tests (see here: https://travis-ci.org/udoprog/relative-path/jobs/540460876#L502). You'll also need to rustfmt things.

Thanks!

**Comment by ratmice** [comment]
Indeed that is more like what I was expecting, Some of the failures just need to change to the new expected output. Others point to more problematic issues with the patch.

It will take me some time to sort through those, and figure out the expected behavior and compare with Path.

**Comment by udoprog** [comment]
How did it go @ratmice?

**Comment by ratmice** [comment]
Sorry, I didn't manage to get it working, and for expediency reasons, I'm currently just passing in the prefix as a separate string to be cut off the path, rather than chomping it when encountering a CURDIR, feel free to close this if desired.  I can just make a new pull request if I get back to it.

**Comment by udoprog** [comment]
Ok! If you still need this, I might be able to look into porting it. For now, I'll close this PR. Thanks!

**Pull request closed without merging**
